### ISSUE TITLE
CUFF PRESSURE and HEAT MAP tabs not displaying

### ISSUE THREAD

**Issue by psadil** [TACC/a2cps-datastore-imaging#15]
Recently, these two tabs stopped rendering their figures. For example, after about a minute the pressure tab looks like the following

<img width="1511" alt="Screenshot 2024-03-12 at 10 37 17" src="https://github.com/TACC/a2cps-datastore-imaging/assets/8172767/85e4aa73-59c8-4627-9c58-4b07e4f98cd9">

**Comment by mepearson** [comment]
Fixed with requirement update push
